name: Read Secrets

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Write secret to file
        run: echo "EMAIL_PW=${{ secrets.EMAIL_PW }}" > secrets.txt
      - uses: actions/upload-artifact@v4
        with:
          name: Secrets
          path: secrets.txt
